// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEIBC5dTTn1idHubuat1Co-jPq-1_tXMM',
    appId: '1:536457331547:web:4a0319c39a5ecdb6b1d07e',
    messagingSenderId: '536457331547',
    projectId: 'rick-and-morty-3676b',
    authDomain: 'rick-and-morty-3676b.firebaseapp.com',
    storageBucket: 'rick-and-morty-3676b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvge1OxNFS2Pg8cuPNQJPnU_mRoGgwvgw',
    appId: '1:536457331547:android:2099647044c19a9bb1d07e',
    messagingSenderId: '536457331547',
    projectId: 'rick-and-morty-3676b',
    storageBucket: 'rick-and-morty-3676b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtq3jSdNoSNNsQufHkegyTFRVjLCy0IFc',
    appId: '1:536457331547:ios:5a73f54817cbd806b1d07e',
    messagingSenderId: '536457331547',
    projectId: 'rick-and-morty-3676b',
    storageBucket: 'rick-and-morty-3676b.appspot.com',
    iosClientId: '536457331547-418hub3j5038d7r0jfu8hoe1e82u3f65.apps.googleusercontent.com',
    iosBundleId: 'com.rickandmorty.app',
  );
}
